name: flucumber
description: Cucumber port for flutter
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  build:
  source_gen:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  build_test:

flutter:
