name: flucumber_generator
description: Generator for flucumber
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  build:
  source_gen:
  path: ^1.8.1
  glob: ^2.1.0
  gherkin: ^3.1.0
  flucumber_annotations:
    path: ../flucumber_annotations

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner:
  build_test: