name: clicker
description: Clicker-game example for flucumber package

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flucumber:
    path: ../../flucumber
  flucumber_generator:
    path: ../../flucumber_generator
  flucumber_annotations:
    path: ../../flucumber_annotations

flutter:
  uses-material-design: true
